#base image
FROM phusion/baseimage:master

#set up app service with runit
RUN mkdir /etc/service/app
COPY scripts/ctci_start.sh /etc/service/app/run
RUN chmod +x /etc/service/app/run

#this is a dev container. set appwatch to kill the app when the binary changes.
RUN mkdir /etc/service/appwatch
COPY scripts/appwatch_start.sh /etc/service/appwatch/run
COPY scripts/appwatch.sh /etc/service/appwatch/appwatch.sh
RUN chmod +x /etc/service/appwatch/appwatch.sh
RUN chmod +x /etc/service/appwatch/run

#set the cwd to deploy (for docker exec -it purposes, mainly)
WORKDIR /deploy

#call the baseimage my_init script, which starts the container properly.
CMD ["/sbin/my_init"]
