version: "3"

services:
  api:
    image: michaelmackend/ctci_api_1_7:dev5
    networks:
      - traefik_public
    volumes:
      - ".:/deploy"
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=ctci_1_7_api"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/ctci/1.7/;Method:POST"
        - "traefik.docker.network=traefik_public"
  web:
    image: michaelmackend/ctci_web_1_7:dev
    networks:
      - traefik_public
    volumes:
      - "./web:/usr/share/nginx/html"
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=ctci_1_7_web"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/ctci/1.7/;Method:GET"
        - "traefik.docker.network=traefik_public"
networks:
  traefik_public:
    external: true

